public:
- ARMSTRONG-S-1
- ARMSTRONG-S-3
- ARMSTRONG-S-9
- SB-S-1
- SB-S-10
- SB-S-11
- SB-S-12
- SB-S-13
- SB-S-14
- SB-S-15
- SB-S-16
- SB-S-17
- SB-S-18
- SB-S-19
- SB-S-2
- SB-S-20
- SB-S-21
- SB-S-22
- SB-S-24
- SB-S-25
- SB-S-26
- SB-S-27
- SB-S-28
- SB-S-29
- SB-S-3
- SB-S-30
- SB-S-31
- SB-S-32
- SB-S-33
- SB-S-34
- SB-S-35
- SB-S-36
- SB-S-37
- SB-S-38
- SB-S-4
- SB-S-40
- SB-S-41
- SB-S-42
- SB-S-5
- SB-S-6
- SB-S-7
- SB-S-8
- SB-S-9
- SCDE-S-1
- SCDE-S-2
- DEPINHO-S-1
- ORKIN-S-1
- SHIVDASANI-I-1
private:
- ARMSTRONG-S-2
- ARMSTRONG-S-4
- ORKIN-S-2
- DEPINHO-S-2
- harvard-CD133_fixed
- SYSCO-I-1
extras:
- ARMSTRONG-I-1 
- SB-S-23
- SB-S-39
- SB-S-43
- SB-S-44
- SB-S-45
- SB-S-46
- SCDE-S-3
- SCDE-S-4
