idmapping: gwas/NIMH_Patient.Rutgers.ID_Translation.txt
priority: gwas/AD-Master-v2.csv
coverage: inputs/alz-priority-regions.bed
fam: gwas/WGS_NIMH.fam

# -- Priority 1/2 re-run missing VCFs/samples
# p1 '51186'
# p2f-g7 '50296', '50948', '51184', '52267'
# 50948 has some confusing labels
# extra illumina sample, missing from AD-Master-v2: 5010533 actually 5010553 in 50296
# -- appears to be a typo
# Not in illumina ['5010623', '5010452']
# 3 families also missing single samples:
# ['5110084', '5010175', '5010500']
# 51105 50391 50722
#
# params:
#  name: alz-p12_redo
#  max_samples: 75
#  families: ['51186', '50296', '50948', '51184', '52267', '51105', '50391', '50722']

# Total = 1476 + 1
# -- Priority 3 final 400
params:
  name: alz-p3f_2
  max_samples: 75
  excludefamilies: ['50105', '50115', '50116', '50122', '50123', '50127', '50130', '50133',
'50143', '50152', '50260', '50261', '50270', '50279', '50288', '50291', '50296',
'50302', '50307', '50319', '50322', '50323', '50328', '50329', '50330', '50331',
'50332', '50334', '50336', '50343', '50354', '50361', '50362', '50367', '50368',
'50369', '50372', '50385', '50388', '50391', '50395', '50397', '50444', '50446',
'50452', '50455', '50456', '50459', '50461', '50500', '50506', '50521', '50523',
'50534', '50563', '50572', '50578', '50581', '50586', '50588', '50589', '50590',
'50593', '50610', '50637', '50638', '50641', '50646', '50648', '50649', '50653',
'50660', '50663', '50668', '50669', '50670', '50676', '50679', '50681', '50722',
'50723', '50732', '50735', '50748', '50771', '50798', '50803', '50808', '50814',
'50840', '50841', '50854', '50857', '50942', '50948', '50962', '50979', '50980',
'50981', '50985', '50986', '50990', '50991', '50993', '50994', '50995', '50997',
'50998', '50999', '51105', '51106', '51107', '51109', '51110', '51111', '51113',
'51114', '51115', '51119', '51123', '51126', '51129', '51134', '51136', '51137',
'51138', '51139', '51146', '51147', '51151', '51153', '51154', '51157', '51158',
'51159', '51161', '51167', '51174', '51175', '51176', '51177', '51180', '51181',
'51184', '51185', '51186', '51192', '51193', '51196', '51200', '51204', '51208',
'51211', '51213', '51214', '51216', '51219', '51223', '51225', '51226', '51227',
'51230', '51238', '51241', '51243', '51250', '51253', '51255', '51257', '51259',
'51263', '51264', '51266', '51267', '51268', '51277', '51278', '52102', '52103',
'52104', '52106', '52107', '52108', '52109', '52110', '52111', '52112', '52113',
'52115', '52121', '52122', '52123', '52125', '52126', '52127', '52133', '52136',
'52137', '52139', '52140', '52142', '52143', '52147', '52148', '52149', '52153',
'52154', '52156', '52157', '52158', '52159', '52161', '52163', '52164', '52165',
'52167', '52170', '52172', '52173', '52174', '52175', '52176', '52177', '52179',
'52180', '52181', '52183', '52184', '52185', '52186', '52187', '52189', '52190',
'52196', '52199', '52200', '52201', '52203', '52207', '52208', '52209', '52215',
'52216', '52218', '52223', '52225', '52226', '52228', '52230', '52231', '52233',
'52234', '52235', '52236', '52240', '52245', '52246', '52249', '52250', '52251',
'52252', '52253', '52254', '52256', '52258', '52259', '52260', '52261', '52262',
'52264', '52267', 'gomez', 'shmaman', '88xxxx']

# -- Priority 3 initial set
# params:
#   name: alz-p3f
#   max_samples: 65
#   # finished p1 and p2
#   excludefamilies: ['50115', '50116', '50127', '50152', '50270',
#   '50288', '50291', '50302', '50307', '50323', '50328', '50329',
#   '50332', '50336', '50354', '50361', '50362', '50452', '50455',
#   '50456', '50523', '50589', '50590', '50593', '50638', '50646',
#   '50670', '50841', '50981', '50986', '50993', '51114', '51126',
#   '51136', '51146', '51147', '51154', '51161', '51181', '51185',
#   '51186', '51192', '51193', '51196', '51200', '51223', '51225',
#   '51227', '51241', '51243', '51253', '52104', '52106', '52111',
#   '52112', '52122', '52123', '52126', '52127', '52143', '52147',
#   '52149', '52153', '52154', '52163', '52164', '52179', '52180',
#   '52185', '52196', '52199', '52203', '52218', '52228', '52230',
#   '52231', '52250', '52251', '52260', 'gomez', 'shmaman', '88xxxx',
#   '50319', '50322', '50330', '50334', '50368', '50521', '50653', '50722',
#   '50723', '50840', '50854', '50942', '50980', '50985', '50994', '50995',
#   '51106', '51123', '51174', '51257', '51277', '51278', '52103', '52109',
#   '52110', '52125', '52140', '52142', '52174', '52259', '50143', '50296',
#   '50391', '50395', '50397', '50446', '50586', '50610', '50663', '50948',
#   '51105', '51109', '51157', '51159', '51180', '51184', '51214', '52115',
#   '52256', '52267',
#   # BAM files need transfer to sanger
#   'exapoe', '51160', '51188', '52248', '50445', '51206', '50996',
#   '51240', '50948', '52134', '52168']
# -- Priority 2 full re-run
#params:
#  name: alz-p2f
#  priority: 2
#  max_samples: 65
# -- gomez
#params:
#  name: alz-gomez
#  families: ['gomez']
# -- shmaman
#params:
#  name: alz-shmaman
#  families: ['shmaman']
# -- Priority 3
#out: tanzi-alz-p3.yaml
#params:
#  name: p3
#  families: ['88xxxx']
# -- Priorty 2 variants
#out: tanzi-alz-p2.yaml
#params:
#  name: p2
#  families: ['51137']
# -- Priorty 1 family selection
# out: config/tanzi-alz-p1.yaml
# params:
#   name: p1
#   priority: 1
#   max_samples: 65

# -- SANGER
sanger:
  inputs:
    - /mnt/lustre/stripe-4M/harvard-illumina/LP*
  base_dir: /home/bradc/data/tanzi_ad
# -- Odyssey
odyssey:
  base_dir: /n/hsphS10/hsphfs1/chb/projects/tanzi_ad/data
  inputs:
    - /n/hsphS10/hsphfs2/tanzi/LP*
